name: conda-cache
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04' ]
        perl: [ '5.26.2' ]
        python: [ '3.7' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - id: get-date
        run: |
          today=$(/bin/date -u '+%Y%m%d')
          echo $today
          echo "today=$today" >> $GITHUB_OUTPUT
      - name: Cache Conda env
        id: cache-conda
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA_PKGS_DIR }}
          key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-perl_v${{ matrix.perl }}
       - name: set up conda
         uses: conda-incubator/setup-miniconda@v2
         with:
           python-version: ${{ matrix.python-version }}
           use-mamba: true
           channels: conda-forge,bioconda,defaults
           mamba-version: "*"
           auto-activate-base: true
           activate-environment: ""
      - name: conda installations
        shell: bash -el {0}
        if: steps.cache-conda.outputs.cache-hit != 'true'
        run: | 
          mamba install -y perl==${{ matrix.perl }}

