name: conda-cache
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04' ]
        perl: [ '5.26.2' ]
        python: [ '3.7' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    # Error on the steps yml for some reason
    steps:
      - name: Get Date
        id: get-date
        run: |
          today=$(/bin/date -u '+%Y%m%d')
          echo $today
          echo "today=$today" >> $GITHUB_OUTPUT
