name: kraken-cache
on: [push]

env:
  KRAKEN_DEFAULT_DB: ~/kraken-database

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04' ]
        perl: [ '5.26.2' ]
        python: [ '3.7' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - name: Cache minikraken
        id: cache-minikraken
        uses: actions/cache@v3
        with:
          path: ~/kraken-database
          key: minikraken-${{ runner.os }}-build-${{ env.cache-name }}
      - name: install minikraken
        if: steps.cache-minikraken.outputs.cache-hit != 'true'
        run: |
          mkdir -v ~/kraken-database
          cd ~/kraken-database
          wget --progress=dot https://ccb.jhu.edu/software/kraken/dl/minikraken_20171101_4GB_dustmasked.tgz
          tar -zxf minikraken_20171101_4GB_dustmasked.tgz
          mv -nv minikraken_20171101_4GB_dustmasked/* . # flatten db dir
          ls -lhSR ~/kraken-database
