name: kraken-cache
on: [push]

env:
  KRAKEN_DEFAULT_DB: ~/kraken-database

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04' ]
        perl: [ '5.26.2' ]
        python: [ '3.7' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - name: Get Date
        id: get-date
        run: |
          today=$(/bin/date -u '+%Y%m%d')
          echo $today
          echo "today=$today" >> $GITHUB_OUTPUT
      - name: check directory 1
        run: |
          pwd
          ls -lhR
      - name: Cache minikraken
        id: cache-minikraken
        uses: actions/cache@v3
        with:
          path: ~/kraken-database
          key: minikraken-${{ runner.os }}-${{ steps.get-date.outputs.today }}
      - name: install minikraken
        if: steps.cache-minikraken.outputs.cache-hit != 'true'
        run: |
          mkdir -v ~/kraken-database
          cd ~/kraken-database
          touch file1 file2 file3
          mkdir taxonomy
      - name: check directory 2
        run: |
          pwd
          ls -lhR
